### ISSUE TITLE
Failure if project contains multiple source directories

### ISSUE THREAD

**Issue by davidburstrom** [exploids/plantuml-from-source#1]
https://github.com/exploids/plantuml-from-source/blob/cd79e9606e367a0a0e154157cdff3752b2d28c8f/src/main/kotlin/com/exploids/plantumlfromsource/gradle/BuildClassDiagramTask.kt#L35
is throwing an exception if there are multiple source directories registered for a source set.
It looks as if it should be possible to iterate over the `allJava.sourceDirectories.files` and add them one by one to the QDoc project.

**Comment by exploids** [comment]
@davidburstrom thanks for bringing this to my attention, unfortunately I currently don't really have time to work on this project, but I'm happy to accept pull requests

**Comment by davidburstrom** [comment]
Hi! Let me know if https://github.com/exploids/plantuml-from-source/pull/2 works well enough for you!

**Comment by exploids** [comment]
Your fix seems to work pretty well, thanks!
